### ISSUE TITLE
Improve button looks

### ISSUE THREAD

**Issue by dawedawe** [amplifying-fsharp/amplifying-fsharp.github.io#16]
I guess the buttons could use a bit of work.

![button](https://user-images.githubusercontent.com/3221269/225597471-3e26e417-497b-4c2b-90bb-1e5b1ba4edad.png)

The black boxes on a white background strike me as a bit too harsh.
But that's of course highly debatable and I'm open to other opinons.

**Comment by nojaf** [comment]
Should be better now.
