### ISSUE TITLE
Split text into visual segments

### ISSUE THREAD

**Issue by dawedawe** [amplifying-fsharp/amplifying-fsharp.github.io#18]
As Edgar already said, the texts could use some love. Everything looks better in boxes 😆 (Or something along those lines)
Maybe a presentation with less need for scrolling down would be nice.

**Comment by nojaf** [comment]
I'm assuming this is about the home page? Best to be very specific for Medhi.

**Comment by dawedawe** [comment]
Yes, it's only about the homepage.

**Comment by nojaf** [comment]
Ok, could you elaborate on this further by maybe taking a screenshot of the homepage with some annotations? It is clear to me but might be difficult for Medhi to understand.

**Comment by dawedawe** [comment]
Currently we have one large rectangle of text with no visual border:

<img width="440" alt="CurrentHomePageAnotated" src="https://user-images.githubusercontent.com/3221269/226288788-4cf7e791-7f97-4e14-b4fc-6f63f55566f9.png">

It could be beneficial to have a visual structure like this:

<img width="1152" alt="sketch" src="https://user-images.githubusercontent.com/3221269/226288606-907ece99-a3fb-4924-9e68-773c8340ffa2.png">

I don't have a super strong opinion on how strong the boxes should be distinguishable from the background. As long as they are somewhat recognizable, I think it would be an improvement.

**Comment by nojaf** [comment]
Should be better now.
